### PR TITLE
Implemented a faker for Swedish id number

### PR DESCRIPTION
**Pull request by tsundberg**
Added a faker for generating valid and invalid Swedish id numbers.

I opened up Faker to get the Locale from it. I'm not sure this is the best way, but it was one way I could get it working.

I added sv-SE.yml so I could generate the format for the id number string. Not sure if this is the preferred way or not.

### CODE REVIEW

**Comment by tsundberg** [comment]
I agree that having the locale being looked up in the IdNumber class is a hack and not much more. Specifying the generator class in the locale specific yml is a much be a better idea.

I also think that the generator class should not live in the main package as the rest of the system Generation is in some sense an implementation detail that should be hidden.

I have a few more ideas of values that are complicated to generate. Swedish company registration number is a specific case that I have a need for. I can also see different national id numbers. An example is Finish. It is similar to the Swedish system, but uses letters as well as digits.

A well thought out solution for these strange more or less values that have very specific rules would be a nice thing.

**Comment by tsundberg** [comment]
Implemented a runtime resolution for the number generator.

This allowed me to remove the need for locating the Locale from a faker. It also allows me to specify a generator in the yml file.

I moved the generators to the package idnumbers so I don't pollute the main package for the faker.

**Comment by trevershick** [comment]
The problem with this implementation is that when the yml files are pulled over from the ruby faker project they're going to be busted. I'm thinking that another yml file needs to be created that has the class name of the Swedish generator in it ( locale specific ) as an extension of IdNumber and then maybe the top level faker class would instantiate the correct type when id() is called.   However it's done, compatibility with the original project yml files seems to be an important idea to keep in mind when working on the project.

**Comment by codingricky** [comment]
Yes @trevershick makes a good point. I'll see if I can extract it out to a separate YML file before merging the change in.

**Comment by codingricky** [comment]
@trevershick @tsundberg merged it in. Considering there wasn't a sv-SE.yml file in the original faker, I thought it was ok to leave it with the version we have here rather than change FakerValueService around to accomodate overriding yml files. I reverted the en.yml and en-us.yml files to their original state so we have compatibility with the original versions and changed the IDNumber method to match. Thanks for your efforts 😄

**Pull request merged**
