### PR TITLE
Fix birthday(): add currentMonth and currentDay 

### PR DESCRIPTION
**Pull request by BlankSergey**
Because it is UI tests sometimes failed with incorrect date
For exapmle: now 2019-11-21
birthday(23, 65) returns 1996-11-26
It is wrong because for birthday 1996-11-26 it is 22 years old now. Not 23

### CODE REVIEW

**Comment by BlankSergey** [comment]
@jmattsson , can you help, please?
CI is unstbale (it was success before).
And coverage magic decreased

**Comment by jmattsson** [comment]
@BlankSergey Nope, I know nothing about this repo. Never touched it in my life, sorry. You probably meant to tag someone else :)

**Comment by beniregev** [comment]
Why not use Java 8 Time API? All dates will be related to UTC and calculations will be correct. For example: in UTC (a.k.a. GMT) it's 2019-11-25 16:00 and in Hong-Kong it's 2019-11-26 01:00AM. Using Java 8 Time API will give us the correct result for both locations, both timezones, without any effort.

**Comment by BlankSergey** [comment]
@jmattsson , I'm sorry :)

> @BlankSergey Nope, I know nothing about this repo. Never touched it in my life, sorry. You probably meant to tag someone else :)

I'm sorry

**Comment by BlankSergey** [comment]
> Why not use Java 8 Time API? All dates will be related to UTC and calculations will be correct. For example: in UTC (a.k.a. GMT) it's 2019-11-25 16:00 and in Hong-Kong it's 2019-11-26 01:00AM. Using Java 8 Time API will give us the correct result for both locations, both timezones, without any effort.

In CONTRIBUTING.md writes:

> Need to maintain compatibility with Java 1.6 (and Android). Therefore any attempt to migrate to 1.6 

> JDKs and above will not be merged back in.

**Pull request merged**
