### PR TITLE
add OscarMovie.java and OscarMovie.yml 

### PR DESCRIPTION
**Pull request by ak-maker**
I choose three of each year's Oscar nominated movies from 2013 to 2022.

### CODE REVIEW

**Comment by ak-maker** [comment]
Including actor/actress, movie name, character, quote and releaseDate. https://github.com/DiUS/java-faker/issues/712 https://github.com/DiUS/java-faker/issues/713

**Comment by bodiam** [comment]
Hi @ak-maker, would you be willing to submit this PR to Datafaker.net too? Is an actively maintained port of this library, and almost identical in the structure.

**Comment by ak-maker** [comment]
Sure, I am willing to do it!

**Comment by ak-maker** [comment]
Hello @bodiam , I have sent it to Datafaker.net. Please check it.

**Pull request closed without merging**
