### PR TITLE
zh-CN.yml增加模拟数据

### PR DESCRIPTION
**Pull request by LiuHao0606**
1.last_name，即姓这块集成了中国的百家姓
2.first_name,  名这块添加了比较热门的名字
3.university.prefix， 增加了大学数据多的城市
4.universitysuffix，增加了大学的类型

### CODE REVIEW

**Comment by LiuHao0606** [comment]
close

**Comment by LiuHao0606** [comment]
Added some Chinese surname data

**Comment by bodiam** [comment]
Would you be able to send this PR to Datafaker.net, this is an active fork of this repo. We will merge and release it right away.

**Comment by LiuHao0606** [comment]
ok

**Comment by LiuHao0606** [comment]
close

**Pull request closed without merging**
