### PR TITLE
create de.yml

### PR DESCRIPTION
**Pull request by elasticjava**
tests fixed

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
@codingricky A new release including this pull request would be highly appreciated.

**Comment by PascalSchumacher** [comment]
@elasticjava I'm obviously not  @codingricky but from my experience a pull request is much more likely to be merged, when it contains just a single well defined change.

I fear this pull request contains too many different changes:
- `Address#secondaryAddress` changed formating of values?
- `Address#streetPrefix` added, I guess this is not useful for every language?
- `Company#suffix` added, data is present for other languages, method to access it was just missing
- `Company#name` changed to include suffix
- `FakeValuesService` changed, not sure why these changes are necessary?
- `pt.yml` changed, not sure why the changes are necessary?
- Added/corrected number handling for locales with `,` as a decimal separator and `.` as decimal group separator

I guess it would be preferable to split this into different pull request, like one with the `de.yml` and the changed `FakerIT` test, another of the number handling etc.

What do you think?

**Comment by codingricky** [comment]
@elasticjava @PascalSchumacher yes I was just reviewing the changes. I agree with @PascalSchumacher. Also it would be good @elasticjava when making changes to the Service classes to accompany them with additional or modified unit tests as well to see why the changes are necessary. I know the IntegrationTest would probably cover it too but the unit tests provide localisation. Sorry for the delay in getting back to you, I was away on leave. Do you think you could make the pull request smaller and also add in a few more unit tests? Thanks

**Comment by codingricky** [comment]
Close this as we do have a de.yml file now.

**Pull request closed without merging**
