### PR TITLE
Add Zelda

### PR DESCRIPTION
**Pull request by robosoul**
Added `Zelda` class with `game` and `character` method supported. 

@codingricky - I plan to add a lot more of the remaining classes like: `RockBand`, `Friends`, `HarryPotter`, etc... Is this preferred way or would you like me to open a ticket for each of the classes?

-Luka

### CODE REVIEW

**Comment by codingricky** [comment]
@robosoul I do prefer separate pull requests, I hope that's ok

**Comment by robosoul** [comment]
@codingricky, I was thinking do you want me to open issues or simply continue as before: one class, one pullreq.

All good. Tnx

**Comment by codingricky** [comment]
@robosoul continue as before, one class, one PR. Also if you could update the readme as well, that would be fantastic.

**Comment by robosoul** [comment]
@codingricky, agreed. PRs coming and I'll update readme as well.

**Pull request merged**
