### PR TITLE
Vehicle Faker

### PR DESCRIPTION
**Pull request by thePantz**
PR regarding #475

### CODE REVIEW

**Comment by thePantz** [comment]
I've added some Canadian license plates but I've come across a strange issue... when resolving `vehicle.license_plate_by_state.ON`,  `fetchObject` treats ON as a boolean so it can never find a match. i.e. it will resolve a list like:

- AB
- BC
- MB
- **TRUE**
- QC

I've intentionally added a failing test to illustrate it.

@codingricky do you know how I can work around this?

**Comment by thePantz** [comment]
Hello, the failed CI tests appear to be unrelated to my changes.  CountryTest.testCapital() has failed in JDK 11. 
@codingricky can you confirm?

**Comment by Tavo5691** [comment]
There seems to be a few erratic tests in the codebase. It also happened to me once when running the tests locally.

Maybe we can open an issue to track this.

**Comment by thePantz** [comment]
I have rebased this branch with the latest changes and the tests have passed. If someone could take a look at this it would be appreciated... Several people have commented that this is a useful feature

**Comment by thePantz** [comment]
The good folks at https://github.com/datafaker-net/datafaker (fork of this repo) have added a vehicle faker among many others. I suggest we all move there

**Pull request closed without merging**
