### PR TITLE
create de.yml

### PR DESCRIPTION
**Pull request by elasticjava**
I added parameters in FakerIT for the new de-locale and ensured that the tests pass.

### CODE REVIEW

**Comment by codingricky** [comment]
The FakerIT test fails. I know travis passes at the moment but if you look at the output of the build https://travis-ci.org/DiUS/java-faker/jobs/104213504 there are failures. For some reason travis is not failing the build. So these failures need to be fixed before your pull request can be merged into master.

**Comment by PascalSchumacher** [comment]
Hi @elasticjava 

as a fellow java-faker user I think having a de.yml would be very nice. :+1: 

Sadly it seems to be missing from the pull request (or github does not display it for some reason)?

**Comment by elasticjava** [comment]
Hello @codingricky @PascalSchumacher,

Thank you for your reply! Please see https://github.com/DiUS/java-faker/pull/56

Best regards!

**Comment by PascalSchumacher** [comment]
#56 was closed because java-faker 0.8 contains a de.yml, so I guess this should be closed too

**Pull request closed without merging**
